services:
    traefik:
        container_name: traefik
        image: "traefik:latest"
        restart: unless-stopped
        networks:
            - traefik
        command:
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.docker
            - --log.level=ERROR
            # ZeroSSL (SSL certificates)
            # -> alternative to Let's Encrypt when rate limits are hit
            # -> comment the following line to get back Let's Encrypt
            # -> delete `acme.json` to switch between Let's Encrypt and ZeroSSL
            - --certificatesresolvers.leresolver.acme.caserver=https://acme.zerossl.com/v2/DV90
            - --certificatesresolvers.leresolver.acme.httpchallenge=true
            - --certificatesresolvers.leresolver.acme.email=${VPS_EMAIL}
            - --certificatesresolvers.leresolver.acme.storage=./acme.json
            - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./acme.json:/acme.json"
        labels:
            - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.http-catchall.entrypoints=web"
            - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

    portainer:
        container_name: portainer
        image: portainer/portainer-ce:lts
        restart: unless-stopped
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - traefik
        labels:
            # Frontend
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`portainer.${VPS_DOMAIN}`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.services.frontend.loadbalancer.server.port=9000"
            - "traefik.http.routers.frontend.service=frontend"
            - "traefik.http.routers.frontend.tls.certresolver=leresolver"

            # Edge
            - "traefik.http.routers.edge.rule=Host(`edge.${VPS_DOMAIN}`)"
            - "traefik.http.routers.edge.entrypoints=websecure"
            - "traefik.http.services.edge.loadbalancer.server.port=8000"
            - "traefik.http.routers.edge.service=edge"
            - "traefik.http.routers.edge.tls.certresolver=leresolver"

networks:
    traefik:
        driver: bridge
        name: traefik

volumes:
    portainer_data:
