services:
    traefik:
        container_name: traefik
        image: "traefik:latest"
        restart: unless-stopped
        networks:
            - traefik
        command:
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.docker
            - --log.level=DEBUG
            - --api.dashboard=true
            - --api.debug=true
            - --providers.file.directory=/etc/traefik/dynamic
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./.dev-certs:/etc/traefik/certs:ro"
            - "./.dev-certs/traefik-dynamic.yml:/etc/traefik/dynamic/tls.yml:ro"
        labels:
            # Global HTTP to HTTPS redirect
            - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.http-catchall.entrypoints=web"
            - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

            # Dashboard
            - "traefik.http.routers.dashboard.rule=Host(`traefik.local.dev`)"
            - "traefik.http.routers.dashboard.entrypoints=websecure"
            - "traefik.http.routers.dashboard.service=api@internal"
            - "traefik.http.routers.dashboard.tls=true"

    portainer:
        container_name: portainer
        image: portainer/portainer-ce:lts
        restart: unless-stopped
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - traefik
        labels:
            # Frontend
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`portainer.local.dev`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.services.frontend.loadbalancer.server.port=9000"
            - "traefik.http.routers.frontend.service=frontend"
            - "traefik.http.routers.frontend.tls=true"

            # Edge
            - "traefik.http.routers.edge.rule=Host(`edge.local.dev`)"
            - "traefik.http.routers.edge.entrypoints=websecure"
            - "traefik.http.services.edge.loadbalancer.server.port=8000"
            - "traefik.http.routers.edge.service=edge"
            - "traefik.http.routers.edge.tls=true"

networks:
    traefik:
        driver: bridge
        name: traefik

volumes:
    portainer_data:
