services:
    nextjs:
        container_name: nextjs
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: runner
        ports:
            - "3000:3000"
        restart: unless-stopped
        volumes:
            - nextjs-volume:/app/.next/cache
        networks:
            - nextjs-network

volumes:
    nextjs-volume:
        driver: local

networks:
    nextjs-network:
        driver: bridge
