services:
    nextjs:
        container_name: nextjs
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: runner
        ports:
            - "3000:3000"
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
